# This is a basic workflow to help you get started with Actions

name: Test & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        
      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1#
        with:
          postgresql db: 'my_db'
          postgresql user: 'test_user'
          postgresql password: 'test_password'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: PGDATABASE=my_db PGUSER=test_user PGPASSWORD=test_password npm t
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: $
          heroku_app_name: $
          heroku_email: $
